// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	OrganizationID string      `json:"organization_id"`
	Name           string      `json:"name"`
	Location       *string     `json:"location"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
}

type Service struct {
	ServiceID          string `json:"service_id"`
	OrganizationID     string `json:"organization_id"`
	ServiceName        string `json:"service_name"`
	ServiceDescription string `json:"service_description"`
	Duration           int32  `json:"duration"`
}
