// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// -- Search services.name
	// SELECT 'services' AS source, service_id, service_name AS value
	// FROM services
	// WHERE to_tsvector(service_name) @@ websearch_to_tsquery($1)
	// UNION ALL
	// -- Search organisations.email
	// SELECT 'organizations' AS source, organization_id, name AS value
	// FROM organizations
	// WHERE to_tsvector(name) @@ websearch_to_tsquery($1);
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (string, error)
	// -- name: GetPaymentStatusByID :one
	// SELECT status
	// FROM payments
	// WHERE payment_id = $1;
	GetBookingsInDateRange(ctx context.Context, arg GetBookingsInDateRangeParams) ([]GetBookingsInDateRangeRow, error)
	GetOrganizationBookings(ctx context.Context) ([]GetOrganizationBookingsRow, error)
	GetOrganizationData(ctx context.Context, email *string) (Organization, error)
	GetOrganizations(ctx context.Context) ([]Organization, error)
	GetPaymentByID(ctx context.Context, paymentID string) (Payment, error)
	// -- name: UpdatePaymentStatus :exec
	// UPDATE payments
	// SET
	//     status = $2,
	//     transaction_ref = $3
	// WHERE payment_id = $1;
	GetSearchResults(ctx context.Context, dollar_1 string) ([]Service, error)
	GetServiceSlots(ctx context.Context, serviceID string) ([]ServiceSlotTemplate, error)
	GetServiceWithOrgTimes(ctx context.Context, serviceID string) (GetServiceWithOrgTimesRow, error)
	GetServicesByOrganization(ctx context.Context, organizationID string) ([]Service, error)
	InsertSlotTemplate(ctx context.Context, arg InsertSlotTemplateParams) error
	UpdateOrganizationData(ctx context.Context, arg UpdateOrganizationDataParams) (Organization, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
