name: Build and Deploy
## This workflow will build the app and deploy the project

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false


on:
  push:
    branches: [ "main" ]
    paths: 
      - "cd/config.yaml"
      - ".github/workflows/build-and-deploy.yaml"
      - "api/**"
      - "app/**"
      - "infra/**"

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read

jobs:
  BuildApi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      - uses: mikefarah/yq@v4.44.3
        with:
            cmd: yq -V


      - name: Read the account id of the Artifact account
        id: read_aws_account_id
        run: |
          AWS_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/config.yaml)
          # Set the value as an output
            echo "aws_account_id=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT
      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.read_aws_account_id.outputs.aws_account_id }}:role/deploy

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          commit_hash="$GITHUB_SHA"
          full_image_tag="${{ steps.read_aws_account_id.outputs.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/api:$commit_hash"

            cd api
            docker build -t "$full_image_tag" .
            docker push $full_image_tag


  BuildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      - uses: mikefarah/yq@v4.44.3
        with:
            cmd: yq -V

      - name: Read the account id of the Artifact account
        id: read_aws_account_id
        run: |
          AWS_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/config.yaml)
          # Set the value as an output
            echo "aws_account_id=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT
      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.read_aws_account_id.outputs.aws_account_id }}:role/deploy

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build React App and Push to Amazon S3
        run: |
          commit_hash="$GITHUB_SHA"
          full_image_tag="${{ steps.read_aws_account_id.outputs.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/api:$commit_hash"
          s3_path="s3://app-artifacts-${{ steps.read_aws_account_id.outputs.aws_account_id }}/$commit_hash/"

            cd app
            npm install
            npm run build
            aws s3 cp ./build "$s3_path" --recursive


  BuildInfraArtifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      - uses: mikefarah/yq@v4.44.3
        with:
            cmd: yq -V

      - name: Read the account id of the Artifact account
        id: read_aws_account_id
        run: |
          AWS_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/config.yaml)
          # Set the value as an output
            echo "aws_account_id=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT
      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.read_aws_account_id.outputs.aws_account_id }}:role/deploy

      - name: Publish Cloudformation templates to Amazon S3
        run: |
          commit_hash="$GITHUB_SHA"
          full_image_tag="${{ steps.read_aws_account_id.outputs.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/api:$commit_hash"
          s3_path="s3://infra-artifacts-${{ steps.read_aws_account_id.outputs.aws_account_id }}/$commit_hash/"

            git submodule update --init --recursive
            aws s3 cp ./infra "$s3_path" --recursive
            

  Deploy:
    needs: [BuildApi, BuildApp, BuildInfraArtifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      - uses: mikefarah/yq@v4.44.3
        with:
            cmd: yq -V

      - name: Read the account id of the Artifact account
        id: read_config
        run: |
          AWS_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/config.yaml)
          AWS_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/config.yaml)
          DOMAIN_NAME=$(yq eval '.domain_name' cd/config.yaml)
          # Set the value as an output
            echo "aws_account_id=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT
            echo "domain_name=$DOMAIN_NAME" >> $GITHUB_OUTPUT
      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.read_config.outputs.aws_account_id }}:role/deploy

      - name: Deploy Environment
        run: |
          
          stack_name="deploy-dev"
          commit_hash="$GITHUB_SHA"
          full_image_tag="${{ steps.read_config.outputs.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/api:$commit_hash"
          infra_bucket_name="infra-artifacts-${{ steps.read_config.outputs.aws_account_id }}"
          s3_path="s3://$infra_bucket_name/$commit_hash"
          domain_name="${{ steps.read_config.outputs.domain_name }}"
          app_bucket_name="app-artifacts-${{ steps.read_config.outputs.aws_account_id }}" 

          cf_template_file="./deploy_env.yaml"
          aws s3 cp "$s3_path/cloudformation/deploy_env.yaml" $cf_template_file

          aws cloudformation deploy \
                  --template-file "$cf_template_file" \
                  --parameter-overrides \
                      EnvId="dev" \
                      InfraArtifactsBucket="$infra_bucket_name" \
                      InfraReleaseHash="$commit_hash" \
                      ApiImageTag="$full_image_tag" \
                      ReleaseTarget="main" \
                      DomainName="$domain_name" \
                      AppReleaseHash="$commit_hash" \
                      AppBucketName="$app_bucket_name" \
                  --stack-name "$stack_name"  \
                  --no-fail-on-empty-changeset \
                  --capabilities CAPABILITY_NAMED_IAM

                distribution_id=$(aws cloudformation describe-stacks --stack-name "$stack_name" --query "Stacks[0].Outputs[?OutputKey=='AppCloudfrontDistributionId'].OutputValue"  --output text )
                aws cloudfront create-invalidation --distribution-id "$distribution_id" --paths '/*'