
# This workflow ensures automatic linting for your Go API using golangci-lint

name: golangci-lint
on:
  push:
    # branches:
    #   - main
    #   - master
  pull_request:


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1